spring.application.name=chat-app-backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/chat-app}
server.port=${PORT:8080}
frontend.url=${FRONTEND_URL:http://localhost:5173,https://vibechat-two.vercel.app}